export const homeObjTwo = {
    lightBg: true,
    primary: false,
    imgStart: true,
    lightTextDesc: false,
    lightTopLine: false,
    lightText: false,
    start: true,
    img: require('../../images/svg-1.svg'),
    alt: 'Image',
    buttonLabel: 'Get Started',
    description: 'We help bussiness owners increase their revenue. Our team of unique specialist can help you acheive your business goals.',
    headLine: 'Custom Product & Software Development Focused On Your Success',
    topLine: 'We Are Pungar',
}